[package]
name = "advent-of-code-2024"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true

[dependencies]
anyhow = "1.0"
itertools = "0.13"
rayon = "1.10"
regex = "1.11"
text_io = "0.1"
